CREATE SCHEMA IF NOT EXISTS slotiq;

CREATE TABLE IF NOT EXISTS slotiq.migrations (
    id SERIAL PRIMARY KEY,
    filename TEXT NOT NULL UNIQUE,
    executed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
